print("hellow python")
print("Hello! " * 3)
print("혼자 공부하다 모르면 동영상 강의를 참고하세요!")
print()
# 하나만 출력합니다.
print("# 하나만 출력합니다.")
print("Hello Python Programming...!")
print()

# 여러 개를 출력합니다.
print("# 여러 개를 출력합니다.")
print(10, 20, 30, 40, 50)
print("안녕하세요", "저의", "이름은", "김선영입니다!")
print()

# 아무것도 입력하지 않으면 단순하게 줄바꿈합니다.
print("# 아무것도 입력하지 않으면 단순하게 줄바꿈합니다.")
print("---- 확인 전용선 ----")
print()
print()
print("---- 확인 전용선 ----")
print(type(234))
print(type("나나"))
print("나나")
print('나나')
print('"안녕하세요"라고 말했습니다')
print("'안녕하세요'라고 말했습니다")
print("\"안녕하세요\"라고 말했습니다")
print('\'안녕하세요\'라고 말했습니다')
print("이름\t나이\t지역")
print("윤인성\t25\t강서구")
print("윤아린\t24\t강서구")
print("구름\t3\t강서구")
print("")
print("문자 선택 연산자에 대해 알아볼까요?")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("---------------------")
print("hello"[-1])
print("hello"[-2])
print("hello"[-3])
print("hello"[-4])
print("hello"[-5])
